# Generated by Django 4.1.2 on 2022-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=13)),
                ("state", models.CharField(max_length=4)),
                ("vehicle_no", models.CharField(max_length=6)),
                ("vehicle_type", models.CharField(max_length=5)),
                ("park_time", models.TimeField()),
                ("park_date", models.DateField()),
            ],
        ),
    ]
