# Generated by Django 4.1.2 on 2022-11-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="vehicle_no",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
