# Generated by Django 4.1.2 on 2022-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_parking_vehicle_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="park_price",
            field=models.IntegerField(default=20),
        ),
    ]
